apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: brl1la8op-nodejs 
  janus-idp.io/tekton: brl1la8op-nodejs
  backstage.io/kubernetes-id: brl1la8op-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: brl1la8op-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  